name: bogsi-development

services:
  sonarqube:
    container_name: sonarqube-service
    image: sonarqube
    depends_on:
      - sonarqube-database
    environment:
      - SONARQUBE_JDBC_USERNAME=sonarqube
      - SONARQUBE_JDBC_PASSWORD=sonarpass
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-database:5432/sonarqube
    volumes:
      - ./.container-data/sonarqube-conf:/opt/sonarqube/conf
      - ./.container-data/sonarqube-data:/opt/sonarqube/data
      - ./.container-data/sonarqube-extensions:/opt/sonarqube/extensions
      - ./.container-data/sonarqube-plugins:/opt/sonarqube/lib/bundled-plugins
    ports:
      - 9000:9000
  
  sonarqube-database:
    container_name: sonarqube-database
    image: postgres:17rc1-alpine3.20
    environment:
      - POSTGRES_DB=sonarqube
      - POSTGRES_USER=sonarqube
      - POSTGRES_PASSWORD=sonarpass
    volumes:
      - ./.container-data/sonarqube-database:/var/lib/postgresql/data
    ports:
      - 5432:5432